### ISSUE TITLE
Hi. Windows 10, VS2013 support question

### ISSUE THREAD

**Issue by dhpark21** [rozmansi/WLANSetEAPUserData#1]
Hi
old day i check win7 that time work it.

but, now i check windows 10. and compile VS2013. not work.
what's wrong?

Thanks

**Comment by rozmansi** [comment]
Wow, this project is still on Visual Studio 2010. I'll upgrade it to Visual Studio 2019 first.

**Comment by rozmansi** [comment]
Upgraded to support Visual Studio 2019 in c1ce01ddad1947d95067ace3b2eb4c21429db908.
