### ISSUE TITLE
The link to the 'EAP-TLS User Properties' XML schema has 404'd

### ISSUE THREAD

**Issue by pbsds** [rozmansi/WLANSetEAPUserData#2]
I'm trying to understand the format used, and came to find that the link to the schema is dead.
Am i correct in guessing that this is the correct shema: https://docs.microsoft.com/en-us/windows/win32/eaphost/eap-tls-user-properties ?

If so, please update the readme

**Comment by rozmansi** [comment]
Thank you for reporting this.
